/* eslint-disable */
import Head from 'next/head';
import Script from 'next/script';
import About from '../components/About';
import Body from '../components/Body';
import Contacts from '../components/Contacts'
import Navbar from '../components/Navbar';
import Projects from '../components/projects'
import Skills from '../components/Skills';
import MessengerCustomerChat from 'react-messenger-customer-chat';

export default function Home() {
  return (
    <div>
      <Head>
      <Script id="62d1605bf9ab8e267a5710d6" src="https://dashboard.chatfuel.com/integration/fb-entry-point.js" async defer/>
        <title>Sam Yusuf | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <script id="62d1605bf9ab8e267a5710d6" src="https://dashboard.chatfuel.com/integration/fb-entry-point.js" async defer></script>
      <Navbar />
      <Body />
      
      <About />
      <Skills />
      <Projects />
      <Contacts />
      
    </div>
  )
}
