/* eslint-disable */
import Head from "next/head";
import Script from "next/script";

export default function Home() {
  return (
    <div>
      <Head>
        <Script
          id="62d1605bf9ab8e267a5710d6"
          src="https://dashboard.chatfuel.com/integration/fb-entry-point.js"
          async
          defer
        />
        <title>Sam Yusuf | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-red-500">
        <h1 className="text-blue-500">come</h1>
      </div>
    </div>
  );
}
